version: "3"
services:
  # chain:
  #   container_name: growr-core
  #   hostname: chain
  #   restart: "always"
  #   image: madgrowr/growr-core-container:0.0.2
  #   ports:
  #     - "8545:8545"
  #   networks:
  #     - growr-network
  # deploy-protocol:
  #   image: madgrowr/growr-core-container:0.0.2
  #   depends_on:
  #     - chain
  #   restart: "no"
  #   entrypoint: [ "sh", "-c", "npm run script:dev:deploy-and-seed-docker"]  
  #   networks:
  #     - growr-network
  app:
    container_name: growr-risk-assesor
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "4000:4000"
    links:
      - mongodb
    depends_on:
      - mongodb
      # - deploy-protocol
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - growr-network
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - growr-network
networks:
  growr-network:
    driver: bridge
volumes:
  growr-volume: